site_name: Dexcount Gradle Plugin
repo_name: dexcount-gradle-plugin
repo_url: https://github.com/keepsafe/dexcount-gradle-plugin
site_url: https://keepsafe.github.io/dexcount-gradle-plugin
site_description: A Gradle plugin to report the number of method references in your APK on every build.
site_author: Benjamin Bader

copyright: "Copyright &copy; 2014-2020 KeepSafe Software, Inc"

theme:
  name: material
  icon:
    logo: material/chart-bar
  favicon: images/favicon.png
  palette:
    primary: indigo
    accent: lime

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - Overview: index.md
  - Options: config.md
  - CI: ci.md

